---
baseURL: https://confident-fermi-3af56e.netlify.app
theme: pure
title: Pure theme for Hugo
defaultContentLanguage: en
footnoteReturnLinkContents: "↩"
hasCJKLanguage: true
paginate: 7
enableEmoji: true
PygmentsCodeFences: false
googleAnalytics: ''
permalinks:
  posts: "/:year/:month/:filename/"
taxonomies:
  category: categories
  tag: tags
  series: series
outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: searchindex
    isPlainText: true
    notAlternative: true
outputs:
  home:
  - HTML
  - RSS
  - SearchIndex
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5
menu:
  main:
  - url: "/about/"
    name: About
    title: About
    weight: 5
    identifier: about
  - url: "/tags/"
    name: Tags
    title: Tags
    weight: 4
    identifier: tags
  - url: "/categories/"
    name: Categories
    title: Categories
    weight: 3
    identifier: categories
  - url: "/posts/"
    name: Archives
    title: Archives
    weight: 2
    identifier: archives
  - url: "/"
    name: Home
    title: Home
    weight: 1
    identifier: home
params:
  since: 2017
  dateFormatToUse: '2006-01-02'
  enablePostCopyright: true
  mainSections:
  - posts
  enableMathJax: true
  highlightjs:
    langs:
    - python
    - javascript
  menuIcons:
    enable: true
    home: icon-home-fill
    archives: icon-archives-fill
    categories: icon-folder
    tags: icon-tags
    repository: icon-project
    books: icon-book-fill
    links: icon-friendship
    about: icon-cup-fill
  profile:
    enabled: true
    avatar: avatar.png
    gravatar: 
    author: xiaoheiAh
    author_title: author title
    author_description: Good Good Study, Day Day Up~
    location: Shanghai, China
    follow: https://github.com/xiaoheiAh
    social:
      links:
        github: https://github.com/xiaoheiAh
        rss: "/index.xml"
      link_tooltip: false
  site:
    logo:
      enabled: true
      width: 40
      height: 40
      url: favicon.ico
    title: Hugo
    favicon: favicon.ico
    board: "<p>enjoy~</p>"
  share:
    enable: true
    sites: weibo,qq,wechat,facebook,twitter
    mobile_sites: weibo,qq,qzone
  comment:
    type: 
    disqus: your_disqus_name
    gitalk:
      owner: 
      admin: 
      repo: 
      ClientID: 
      ClientSecret: 
    valine:
      appid: 
      appkey: 
      notify: 
      verify: 
      placeholder: enjoy~
      avatar: mm
      meta: nick,mail
      pageSize: 10
      visitor: false
  donate:
    enable: false
    wechatpay:
      qrcode: donate/wechatpayimg.png
      title: 微信支付
    alipay:
      qrcode: donate/alipayimg.png
      title: 支付宝
  pv:
    busuanzi:
      enable: false
    leancloud:
      enable: false
      app_id: 
      app_key: 
  postCount:
    enable: true
    wordcount: true
    min2read: true
  config:
    skin: theme-black
    layout: main-center
    excerpt_link: Read More
    toc: true
  sidebar: right
  search:
    enable: true
  widgets:
  - board
  - category
  - tag
  - recent_posts
